### ISSUE TITLE
Date是否支持自定义格式

### ISSUE THREAD

**Issue by aipan** [childe/gohangout#155]
Date不能解析 2006-01-02 15:04:05,000 这种格式，数据如下 2021-10-29 20:27:07,490

**Comment by childe** [comment]
应该是golang库不支持。 要先把逗号换掉。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: aipan ***@***.***&gt;
发送时间: 2021年11月25日 16:10
收件人: childe/gohangout ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [childe/gohangout] Date是否支持自定义格式 (Issue #155)





 
Date不能解析 2006-01-02 15:04:05,000 这种格式，数据如下 2021-10-29 20:27:07,490
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
